In [1]:
import numpy as np
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Dense, SimpleRNN, LSTM, GRU, Bidirectional, Embedding, Input, Concatenate, Dot, Activation,Attention
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [2]:
max_features = 1000

In [3]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)

# Concatenate the training and testing data
X = np.concatenate((X_train, X_test), axis=0)
y = np.concatenate((y_train, y_test), axis=0)

# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

max_length = 100

In [4]:
# Pad sequences to the same length
X_train = pad_sequences(X_train, maxlen=max_length)
X_test = pad_sequences(X_test, maxlen=max_length)

In [5]:
# Convert sequences to one-hot encoded vectors
X_train = np.array([to_categorical(seq, num_classes=max_features) for seq in X_train])
X_test = np.array([to_categorical(seq, num_classes=max_features) for seq in X_test])
X_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [6]:
# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2)

In [7]:
# Simple RNN
model_rnn = Sequential()
model_rnn.add(SimpleRNN(100, input_shape=(max_length, max_features)))
model_rnn.add(Dense(1, activation='sigmoid'))

In [ ]:
model_rnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model_rnn.fit(X_train, y_train, batch_size=64, epochs=50, validation_data=(X_val, y_val))
scores_rnn = model_rnn.evaluate(X_test, y_test, verbose=0)
print("Simple RN N Test Accuracy: %.2f%%" % (scores_rnn[1] * 100))

Epoch 1/50
500/500 [==============================] - 79s 153ms/step - loss: 0.6077 - accuracy: 0.6494 - val_loss: 0.4573 - val_accuracy: 0.7887
Epoch 2/50
500/500 [==============================] - 73s 146ms/step - loss: 0.4568 - accuracy: 0.7897 - val_loss: 0.4291 - val_accuracy: 0.8081
Epoch 3/50
500/500 [==============================] - 70s 140ms/step - loss: 0.4357 - accuracy: 0.8019 - val_loss: 0.4198 - val_accuracy: 0.8160
Epoch 4/50
500/500 [==============================] - 69s 138ms/step - loss: 0.4203 - accuracy: 0.8112 - val_loss: 0.4159 - val_accuracy: 0.8164
Epoch 5/50
500/500 [==============================] - 74s 148ms/step - loss: 0.4057 - accuracy: 0.8204 - val_loss: 0.4409 - val_accuracy: 0.8074
Epoch 6/50
500/500 [==============================] - 76s 152ms/step - loss: 0.4031 - accuracy: 0.8229 - val_loss: 0.4187 - val_accuracy: 0.8126
Epoch 7/50
500/500 [==============================] - 75s 149ms/step - loss: 0.4021 - accuracy: 0.8237 - val_loss: 0.4152 - val_ac

In [20]:
from sklearn.metrics import confusion_matrix
# Evaluate the model on the test set
y_pred_prob = model_rnn.predict(X_test)
y_pred = np.round(y_pred_prob).flatten()

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

313/313 [==============================] - 7s 21ms/step
Confusion Matrix:
[[4091  947]
 [1094 3868]]


In [21]:
# LSTM
model_lstm = Sequential()
model_lstm.add(LSTM(100, input_shape=(max_length, max_features)))
model_lstm.add(Dense(1, activation='sigmoid'))

In [22]:
model_lstm.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model_lstm.fit(X_train, y_train, batch_size=64, epochs=5, validation_data=(X_val, y_val))
scores_lstm = model_lstm.evaluate(X_test, y_test, verbose=0)
print("LSTM Test Accuracy: %.2f%%" % (scores_lstm[1] * 100))

Epoch 1/5
500/500 [==============================] - 111s 219ms/step - loss: 0.4566 - accuracy: 0.7821 - val_loss: 0.3799 - val_accuracy: 0.8279
Epoch 2/5
500/500 [==============================] - 121s 241ms/step - loss: 0.3705 - accuracy: 0.8361 - val_loss: 0.3846 - val_accuracy: 0.8265
Epoch 3/5
500/500 [==============================] - 123s 246ms/step - loss: 0.3465 - accuracy: 0.8464 - val_loss: 0.4127 - val_accuracy: 0.8227
Epoch 4/5
500/500 [==============================] - 118s 235ms/step - loss: 0.3350 - accuracy: 0.8537 - val_loss: 0.3799 - val_accuracy: 0.8279
Epoch 5/5
500/500 [==============================] - 125s 249ms/step - loss: 0.3164 - accuracy: 0.8625 - val_loss: 0.3873 - val_accuracy: 0.8325
LSTM Test Accuracy: 83.35%


In [23]:
# Evaluate the model on the test set
y_pred_prob = model_lstm.predict(X_test)
y_pred = np.round(y_pred_prob).flatten()

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

313/313 [==============================] - 15s 45ms/step
Confusion Matrix:
[[4324  714]
 [ 951 4011]]


In [24]:
# GRU
model_gru = Sequential()
model_gru.add(GRU(100, input_shape=(max_length, max_features)))
model_gru.add(Dense(1, activation='sigmoid'))

In [25]:
model_gru.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model_gru.fit(X_train, y_train, batch_size=64, epochs=5, validation_data=(X_val, y_val))
scores_gru = model_gru.evaluate(X_test, y_test, verbose=0)
print("GRU Test Accuracy: %.2f%%" % (scores_gru[1] * 100))

Epoch 1/5
500/500 [==============================] - 113s 222ms/step - loss: 0.4670 - accuracy: 0.7666 - val_loss: 0.3852 - val_accuracy: 0.8278
Epoch 2/5
500/500 [==============================] - 113s 226ms/step - loss: 0.3622 - accuracy: 0.8382 - val_loss: 0.3681 - val_accuracy: 0.8334
Epoch 3/5
500/500 [==============================] - 115s 229ms/step - loss: 0.3342 - accuracy: 0.8546 - val_loss: 0.3708 - val_accuracy: 0.8342
Epoch 4/5
500/500 [==============================] - 114s 228ms/step - loss: 0.3094 - accuracy: 0.8653 - val_loss: 0.3904 - val_accuracy: 0.8257
Epoch 5/5
500/500 [==============================] - 112s 223ms/step - loss: 0.2928 - accuracy: 0.8739 - val_loss: 0.3798 - val_accuracy: 0.8379
GRU Test Accuracy: 84.14%


In [26]:
# Evaluate the model on the test set
y_pred_prob = model_gru.predict(X_test)
y_pred = np.round(y_pred_prob).flatten()

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

313/313 [==============================] - 11s 32ms/step
Confusion Matrix:
[[4296  742]
 [ 844 4118]]


In [27]:
# Bidirectional LSTM
model_bilstm = Sequential()
model_bilstm.add(Bidirectional(LSTM(100), input_shape=(max_length, max_features)))
model_bilstm.add(Dense(1, activation='sigmoid'))

In [28]:
model_bilstm.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model_bilstm.fit(X_train, y_train, batch_size=64, epochs=5, validation_data=(X_val, y_val))
scores_bilstm = model_bilstm.evaluate(X_test, y_test, verbose=0)
print("Bidirectional LSTM Test Accuracy: %.2f%%" % (scores_bilstm[1] * 100))

Epoch 1/5
500/500 [==============================] - 201s 395ms/step - loss: 0.4952 - accuracy: 0.7581 - val_loss: 0.4218 - val_accuracy: 0.8066
Epoch 2/5
500/500 [==============================] - 191s 382ms/step - loss: 0.3726 - accuracy: 0.8351 - val_loss: 0.4061 - val_accuracy: 0.8240
Epoch 3/5
500/500 [==============================] - 192s 384ms/step - loss: 0.3488 - accuracy: 0.8471 - val_loss: 0.3724 - val_accuracy: 0.8317
Epoch 4/5
500/500 [==============================] - 191s 382ms/step - loss: 0.3297 - accuracy: 0.8562 - val_loss: 0.3762 - val_accuracy: 0.8284
Epoch 5/5
500/500 [==============================] - 187s 374ms/step - loss: 0.3037 - accuracy: 0.8689 - val_loss: 0.3783 - val_accuracy: 0.8375
Bidirectional LSTM Test Accuracy: 82.86%


In [29]:
# Evaluate the model on the test set
y_pred_prob = model_bilstm.predict(X_test)
y_pred = np.round(y_pred_prob).flatten()

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

313/313 [==============================] - 30s 89ms/step
Confusion Matrix:
[[4060  978]
 [ 736 4226]]


In [36]:
#Bi-LSTM with Attention

# Reshape the labels to match the shape of the logits
y_train = np.reshape(y_train, (-1, 1))
y_test = np.reshape(y_test, (-1,  1))
y_val = np.reshape(y_val, (-1,  1))
# Define the input layer
input_seq = Input(shape=(max_length, max_features))

# Bidirectional LSTM layer
lstm_units = 100
lstm_layer = Bidirectional(LSTM(lstm_units, return_sequences=True))(input_seq)

# Attention mechanism
attention = Attention()([lstm_layer, lstm_layer])

# Concatenate the LSTM output and attention weights
concatenated = Concatenate(axis=-1)([lstm_layer, attention])
# Dense layer for classification
output = Dense(1, activation='sigmoid')(concatenated)

# Create the model
model = Model(inputs=input_seq, outputs=output)

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
batch_size = 64
epochs = 5
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_data=(X_val, y_val))

# Evaluate the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Bidirectional LSTM with Attention Test Accuracy: %.2f%%" % (scores[1] * 100))

Epoch 1/5
500/500 [==============================] - 319s 633ms/step - loss: 0.4532 - accuracy: 0.7845 - val_loss: 0.3803 - val_accuracy: 0.8286
Epoch 2/5
500/500 [==============================] - 313s 626ms/step - loss: 0.3666 - accuracy: 0.8384 - val_loss: 0.4014 - val_accuracy: 0.8158
Epoch 3/5
500/500 [==============================] - 317s 633ms/step - loss: 0.3565 - accuracy: 0.8441 - val_loss: 0.3707 - val_accuracy: 0.8327
Epoch 4/5
500/500 [==============================] - 319s 638ms/step - loss: 0.3393 - accuracy: 0.8521 - val_loss: 0.3732 - val_accuracy: 0.8332
Epoch 5/5
500/500 [==============================] - 321s 642ms/step - loss: 0.3257 - accuracy: 0.8577 - val_loss: 0.3657 - val_accuracy: 0.8365
Bidirectional LSTM with Attention Test Accuracy: 83.56%


In [67]:
print(X_test.shape)
y_test = np.reshape(y_test, (-1,))
print(y_test.shape)

(10000, 100, 1000)
(10000,)


In [69]:
# Evaluate the model on the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob >= 0.5).astype(int).flatten()
# Reshape y_pred to match the shape of y_test
y_pred_reshaped = y_pred[:y_test..
                         shape[0]]

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred_reshaped)
print("Confusion Matrix:")
print(cm)

313/313 [==============================] - 55s 175ms/step
Confusion Matrix:
[[2983 2055]
 [2857 2105]]


In [70]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=max_features)

In [71]:
# Obtain user input for the review
user_review = input("Enter your review: ")

# Preprocess the user input
user_input = tokenizer.texts_to_sequences([user_review])
user_input = pad_sequences(user_input, maxlen=max_length)

# Convert user input to one-hot encoded vectors
user_input = np.array([to_categorical(seq, num_classes=max_features) for seq in user_input])

# Reshape the user input to match the input shape of the model
user_input = np.reshape(user_input, (1, max_length, max_features))

# Make predictions using the trained model
prediction = model.predict(user_input)

# Interpret the prediction
sentiment = ""
if prediction[0][0] < 0.5:
    sentiment = "Negative"
elif prediction[0][0] > 0.5:
    sentiment = "Positive"
else:
    sentiment = "Neutral"

# Print the predicted sentiment
print("Predicted sentiment: " + sentiment)

Enter your review: this movie is too overated.
1/1 [==============================] - 0s 66ms/step
Predicted sentiment: Negative
